// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FarmField } from "./FarmField";

export interface FarmFieldGroup { id: number, name: string, farm_id: number, fields: Array<FarmField>, }