// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FarmFieldGroup { id: number, name: string, farm_id: number, fields: Array<number>, draw_color: string, }