// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FarmField { id: number, name: string, map_polygon_string: string, farm_id: number, farm_field_group_id: number | null, }