// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FarmFieldMeta = { id: number, name: string, farm_id: number, farm_field_group_id: number | null, farm_field_group_name: string | null, };