// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldEventValue =
  | { kind: "int"; value: number }
  | { kind: "unit_int"; value: number; unit: string }
  | { kind: "text"; value: string };
