// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldEventTypeField } from "./FieldEventTypeField";

export type FieldEventType = {
  id: number;
  name: string;
  fields: Array<FieldEventTypeField>;
};
