// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupHarvestAgg = {
  group_id: number;
  group_name: string;
  group_color: string;
  value: number;
};
