// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarvestTimeseries } from "./HarvestTimeseries";

export type HarvestAggregated = {
  type_id: number;
  type_name: string;
  harvests: Array<HarvestTimeseries>;
};
