// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarvestEvent } from "./HarvestEvent";
import type { HarvestParams } from "./HarvestParams";

export type HarvestPagination = { params: HarvestParams, events: Array<HarvestEvent>, };