// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HarvestEvent = { id: number, value: number, time: string, field_id: number, type_name: string, type_id: number, };